### ISSUE TITLE
Trying to install Tkinker without success

### ISSUE THREAD

**Issue by yvann-ba** [AshMartian/ComfyUI-DirGir#4]
Hey ! 
Thanks for the pack nodes, the features really interest me but I don't have Tkinker install on my python env on ComfyUI. I tried to install it manually but doesn't work. I'm on Windows 11 with the "ComfyUI_Windows_portable" version.
Can you help me please ?

**Comment by AshMartian** [comment]
Hello! I didn’t consider ComfyUI with the portable version. I’d like to wrap the Tkinker import in a try/catch, and hide the browse button if not installed. This way it will at least work and not crash the Comfy server. I’ll setup a portable version and experiment!

**Comment by AshMartian** [comment]
I just merged a work-around that should at least let you use the nodes. Tkinter is now tried on import, and if failed it's communicated to the front end where the button will be disabled. 

The source of the issue goes into how the portable version includes it's own Python binary, which does not include tcl/tk. Might be able to work around it if these binaries are set with `TCL_LIBRARY` and `TK_LIBRARY` environment variables pointing to their location. However I'm not entirely sure and wanted to make sure the nodes work without the dependency. You can still paste in a directory into the Picker node, or use a simple string into the Loopy Dir node.

![image](https://github.com/AshMartian/ComfyUI-DirGir/assets/1238942/b77ffc76-f671-4177-9028-f050289a23e2)

**Comment by yvann-ba** [comment]
it works perfectly now. Thanks, you're awesome !!
