### ISSUE TITLE
Feature Request: Add Random File Selection for Enhanced Testing Automation

### ISSUE THREAD

**Issue by yvann-ba** [AshMartian/ComfyUI-DirGir#7]
I think it would be very interesting to have the ability to randomly select a file from a folder, for automation purposes, and test different parameter combinations in a workflow.

![image](https://github.com/AshMartian/ComfyUI-DirGir/assets/97234242/194107fc-ef72-49ae-ba21-4007d4adf35f)

I use it to choose an entry for IPadapter (and also a checkpoint and lora with the same way of doing it) automatically for a vid2vid process so I can try a lot of style overnight so random sorting would be more interesting because otherwise I always have the same combination between (checkpoint/lora/ipadapter).

Translated with DeepL.com (free version)

![image](https://github.com/AshMartian/ComfyUI-DirGir/assets/97234242/a8546659-dc57-496c-9bbb-b5f4aaa9893c)
(adding a random option to the sort option for this node)
Thanks a lot for your work, it really help me create !

**Comment by AshMartian** [comment]
I'm glad it's working for you and is helping create more!

Random sort order is a great idea, implemented in #8 

![image](https://github.com/AshMartian/ComfyUI-DirGir/assets/1238942/8fd7582b-7a39-4943-8ec1-f8c8109d1881)

![image](https://github.com/AshMartian/ComfyUI-DirGir/assets/1238942/0ed91134-6a89-4743-8dd0-fa7d801eba7a)
